/* File generated by the BNF Converter (bnfc 2.9.3). */

/*** Pretty Printer and Abstract Syntax Viewer ***/

#include <string>
#include "Printer.H"
#define INDENT_WIDTH 2


//You may wish to change render
void PrintAbsyn::render(Char c)
{
  if (c == '{')
  {
     onEmptyLine();
     bufAppend(c);
     _n_ = _n_ + INDENT_WIDTH;
     bufAppend('\n');
     indent();
  }
  else if (c == '(' || c == '[')
     bufAppend(c);
  else if (c == ')' || c == ']')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == '}')
  {
     _n_ = _n_ - INDENT_WIDTH;
     onEmptyLine();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ',')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend(' ');
  }
  else if (c == ';')
  {
     removeTrailingWhitespace();
     bufAppend(c);
     bufAppend('\n');
     indent();
  }
  else if (c == ' ') bufAppend(c);
  else if (c == 0) return;
  else
  {
     bufAppend(c);
     bufAppend(' ');
  }
}

void PrintAbsyn::render(String s)
{
  render(s.c_str());
}

bool allIsSpace(const char *s)
{
  char c;
  while ((c = *s++))
    if (! isspace(c)) return false;
  return true;
}

void PrintAbsyn::render(const char *s)
{
  if (*s) /* C string not empty */
  {
    if (allIsSpace(s)) {
      backup();
      bufAppend(s);
    } else {
      bufAppend(s);
      bufAppend(' ');
    }
  }
}

void PrintAbsyn::indent()
{
  int n = _n_;
  while (--n >= 0)
    bufAppend(' ');
}

void PrintAbsyn::backup()
{
  if (cur_ && buf_[cur_ - 1] == ' ')
    buf_[--cur_] = 0;
}

void PrintAbsyn::removeTrailingSpaces()
{
  while (cur_ && buf_[cur_ - 1] == ' ') --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::removeTrailingWhitespace()
{
  while (cur_ && (buf_[cur_ - 1] == ' ' || buf_[cur_ - 1] == '\n')) --cur_;
  buf_[cur_] = 0;
}

void PrintAbsyn::onEmptyLine()
{
  removeTrailingSpaces();
  if (cur_ && buf_[cur_ - 1 ] != '\n') bufAppend('\n');
  indent();
}

PrintAbsyn::PrintAbsyn(void)
{
  _i_ = 0; _n_ = 0;
  buf_ = 0;
  bufReset();
}

PrintAbsyn::~PrintAbsyn(void)
{
}

char *PrintAbsyn::print(Visitable *v)
{
  _i_ = 0; _n_ = 0;
  bufReset();
  v->accept(this);
  return buf_;
}

void PrintAbsyn::visitProgram(Program *p) {} //abstract class

void PrintAbsyn::visitProgramFunction(ProgramFunction *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->function_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitProgram1(Program1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->function_->accept(this);
  _i_ = 0; p->program_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitFunction(Function *p) {} //abstract class

void PrintAbsyn::visitFunction1(Function1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_1);
  _i_ = 0; p->arglist_->accept(this);
  render("->");
  visitIdent(p->ident_2);
  render(':');
  _i_ = 0; p->letins_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArgList(ArgList *p) {} //abstract class

void PrintAbsyn::visitArgListIdent(ArgListIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitArgList1(ArgList1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  _i_ = 0; p->arglist_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLetIns(LetIns *p) {} //abstract class

void PrintAbsyn::visitLetIns1(LetIns1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->letin_->accept(this);
  _i_ = 0; p->optionalhash_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLetIns2(LetIns2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->letin_->accept(this);
  _i_ = 0; p->optionalhash_->accept(this);
  _i_ = 0; p->letins_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOptionalHash(OptionalHash *p) {} //abstract class

void PrintAbsyn::visitOptionalHash1(OptionalHash1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);


  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitOptionalHash2(OptionalHash2 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  render('#');

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLetIn(LetIn *p) {} //abstract class

void PrintAbsyn::visitLetIn1(LetIn1 *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);
  render('=');
  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitLetInExpr(LetInExpr *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  _i_ = 0; p->expr_->accept(this);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExpr(Expr *p) {} //abstract class

void PrintAbsyn::visitExprIdent(ExprIdent *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitIdent(p->ident_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExprInteger(ExprInteger *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitInteger(p->integer_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExprDouble(ExprDouble *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitDouble(p->double_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitExprString(ExprString *p)
{
  int oldi = _i_;
  if (oldi > 0) render(_L_PAREN);

  visitString(p->string_);

  if (oldi > 0) render(_R_PAREN);
  _i_ = oldi;
}

void PrintAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  render(tmp);
}

void PrintAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  render(tmp);
}

void PrintAbsyn::visitChar(Char c)
{
  char tmp[4];
  sprintf(tmp, "'%c'", c);
  render(tmp);
}

void PrintAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
  bufAppend(' ');
}

void PrintAbsyn::visitIdent(String s)
{
  render(s);
}

ShowAbsyn::ShowAbsyn(void)
{
  buf_ = 0;
  bufReset();
}

ShowAbsyn::~ShowAbsyn(void)
{
}

char *ShowAbsyn::show(Visitable *v)
{
  bufReset();
  v->accept(this);
  return buf_;
}

void ShowAbsyn::visitProgram(Program *p) {} //abstract class

void ShowAbsyn::visitProgramFunction(ProgramFunction *p)
{
  bufAppend('(');
  bufAppend("ProgramFunction");
  bufAppend(' ');
  bufAppend('[');
  if (p->function_)  p->function_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitProgram1(Program1 *p)
{
  bufAppend('(');
  bufAppend("Program1");
  bufAppend(' ');
  bufAppend('[');
  if (p->function_)  p->function_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->program_)  p->program_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitFunction(Function *p) {} //abstract class

void ShowAbsyn::visitFunction1(Function1 *p)
{
  bufAppend('(');
  bufAppend("Function1");
  bufAppend(' ');
  visitIdent(p->ident_1);
  bufAppend(' ');
  bufAppend('[');
  if (p->arglist_)  p->arglist_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  visitIdent(p->ident_2);
  bufAppend(' ');
  bufAppend('[');
  if (p->letins_)  p->letins_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitArgList(ArgList *p) {} //abstract class

void ShowAbsyn::visitArgListIdent(ArgListIdent *p)
{
  bufAppend('(');
  bufAppend("ArgListIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitArgList1(ArgList1 *p)
{
  bufAppend('(');
  bufAppend("ArgList1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->arglist_)  p->arglist_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitLetIns(LetIns *p) {} //abstract class

void ShowAbsyn::visitLetIns1(LetIns1 *p)
{
  bufAppend('(');
  bufAppend("LetIns1");
  bufAppend(' ');
  bufAppend('[');
  if (p->letin_)  p->letin_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->optionalhash_)  p->optionalhash_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitLetIns2(LetIns2 *p)
{
  bufAppend('(');
  bufAppend("LetIns2");
  bufAppend(' ');
  bufAppend('[');
  if (p->letin_)  p->letin_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->optionalhash_)  p->optionalhash_->accept(this);
  bufAppend(']');
  bufAppend(' ');
  bufAppend('[');
  if (p->letins_)  p->letins_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitOptionalHash(OptionalHash *p) {} //abstract class

void ShowAbsyn::visitOptionalHash1(OptionalHash1 *p)
{
  bufAppend("OptionalHash1");
}
void ShowAbsyn::visitOptionalHash2(OptionalHash2 *p)
{
  bufAppend("OptionalHash2");
}
void ShowAbsyn::visitLetIn(LetIn *p) {} //abstract class

void ShowAbsyn::visitLetIn1(LetIn1 *p)
{
  bufAppend('(');
  bufAppend("LetIn1");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitLetInExpr(LetInExpr *p)
{
  bufAppend('(');
  bufAppend("LetInExpr");
  bufAppend(' ');
  bufAppend('[');
  if (p->expr_)  p->expr_->accept(this);
  bufAppend(']');
  bufAppend(')');
}
void ShowAbsyn::visitExpr(Expr *p) {} //abstract class

void ShowAbsyn::visitExprIdent(ExprIdent *p)
{
  bufAppend('(');
  bufAppend("ExprIdent");
  bufAppend(' ');
  visitIdent(p->ident_);
  bufAppend(')');
}
void ShowAbsyn::visitExprInteger(ExprInteger *p)
{
  bufAppend('(');
  bufAppend("ExprInteger");
  bufAppend(' ');
  visitInteger(p->integer_);
  bufAppend(')');
}
void ShowAbsyn::visitExprDouble(ExprDouble *p)
{
  bufAppend('(');
  bufAppend("ExprDouble");
  bufAppend(' ');
  visitDouble(p->double_);
  bufAppend(')');
}
void ShowAbsyn::visitExprString(ExprString *p)
{
  bufAppend('(');
  bufAppend("ExprString");
  bufAppend(' ');
  visitString(p->string_);
  bufAppend(')');
}
void ShowAbsyn::visitInteger(Integer i)
{
  char tmp[20];
  sprintf(tmp, "%d", i);
  bufAppend(tmp);
}
void ShowAbsyn::visitDouble(Double d)
{
  char tmp[24];
  sprintf(tmp, "%.15g", d);
  bufAppend(tmp);
}
void ShowAbsyn::visitChar(Char c)
{
  bufAppend('\'');
  bufAppend(c);
  bufAppend('\'');
}
void ShowAbsyn::visitString(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}
void ShowAbsyn::visitIdent(String s)
{
  bufAppend('\"');
  bufAppend(s);
  bufAppend('\"');
}


