/* File generated by the BNF Converter (bnfc 2.9.3). */

/*** Visitor Design Pattern Skeleton. ***/
/* This implements the common visitor design pattern.
   Note that this method uses Visitor-traversal of lists, so
   List->accept() does NOT traverse the list. This allows different
   algorithms to use context information differently. */

#include "Skeleton.H"



void Skeleton::visitProgram(Program *t) {} //abstract class
void Skeleton::visitFunction(Function *t) {} //abstract class
void Skeleton::visitArgList(ArgList *t) {} //abstract class
void Skeleton::visitLetIns(LetIns *t) {} //abstract class
void Skeleton::visitOptionalHash(OptionalHash *t) {} //abstract class
void Skeleton::visitLetIn(LetIn *t) {} //abstract class
void Skeleton::visitExpr(Expr *t) {} //abstract class

void Skeleton::visitProgramFunction(ProgramFunction *program_function)
{
  /* Code For ProgramFunction Goes Here */

  if (program_function->function_) program_function->function_->accept(this);

}

void Skeleton::visitProgram1(Program1 *program)
{
  /* Code For Program1 Goes Here */

  if (program->function_) program->function_->accept(this);
  if (program->program_) program->program_->accept(this);

}

void Skeleton::visitFunction1(Function1 *function)
{
  /* Code For Function1 Goes Here */

  visitIdent(function->ident_1);
  if (function->arglist_) function->arglist_->accept(this);
  visitIdent(function->ident_2);
  if (function->letins_) function->letins_->accept(this);

}

void Skeleton::visitArgListIdent(ArgListIdent *arg_list_ident)
{
  /* Code For ArgListIdent Goes Here */

  visitIdent(arg_list_ident->ident_);

}

void Skeleton::visitArgList1(ArgList1 *arg_list)
{
  /* Code For ArgList1 Goes Here */

  visitIdent(arg_list->ident_);
  if (arg_list->arglist_) arg_list->arglist_->accept(this);

}

void Skeleton::visitLetIns1(LetIns1 *let_ins)
{
  /* Code For LetIns1 Goes Here */

  if (let_ins->letin_) let_ins->letin_->accept(this);
  if (let_ins->optionalhash_) let_ins->optionalhash_->accept(this);

}

void Skeleton::visitLetIns2(LetIns2 *let_ins)
{
  /* Code For LetIns2 Goes Here */

  if (let_ins->letin_) let_ins->letin_->accept(this);
  if (let_ins->optionalhash_) let_ins->optionalhash_->accept(this);
  if (let_ins->letins_) let_ins->letins_->accept(this);

}

void Skeleton::visitOptionalHash1(OptionalHash1 *optional_hash)
{
  /* Code For OptionalHash1 Goes Here */


}

void Skeleton::visitOptionalHash2(OptionalHash2 *optional_hash)
{
  /* Code For OptionalHash2 Goes Here */


}

void Skeleton::visitLetIn1(LetIn1 *let_in)
{
  /* Code For LetIn1 Goes Here */

  visitIdent(let_in->ident_);
  if (let_in->expr_) let_in->expr_->accept(this);

}

void Skeleton::visitLetInExpr(LetInExpr *let_in_expr)
{
  /* Code For LetInExpr Goes Here */

  if (let_in_expr->expr_) let_in_expr->expr_->accept(this);

}

void Skeleton::visitExprIdent(ExprIdent *expr_ident)
{
  /* Code For ExprIdent Goes Here */

  visitIdent(expr_ident->ident_);

}

void Skeleton::visitExprInteger(ExprInteger *expr_integer)
{
  /* Code For ExprInteger Goes Here */

  visitInteger(expr_integer->integer_);

}

void Skeleton::visitExprDouble(ExprDouble *expr_double)
{
  /* Code For ExprDouble Goes Here */

  visitDouble(expr_double->double_);

}

void Skeleton::visitExprString(ExprString *expr_string)
{
  /* Code For ExprString Goes Here */

  visitString(expr_string->string_);

}



void Skeleton::visitInteger(Integer x)
{
  /* Code for Integer Goes Here */
}

void Skeleton::visitChar(Char x)
{
  /* Code for Char Goes Here */
}

void Skeleton::visitDouble(Double x)
{
  /* Code for Double Goes Here */
}

void Skeleton::visitString(String x)
{
  /* Code for String Goes Here */
}

void Skeleton::visitIdent(Ident x)
{
  /* Code for Ident Goes Here */
}



