-- File generated by the BNF Converter (bnfc 2.9.3).

{-# LANGUAGE GeneralizedNewtypeDeriving #-}

-- | The abstract syntax of language shre.

module AbsShre where

import Prelude (Double, Integer, String)
import qualified Prelude as C (Eq, Ord, Show, Read)
import qualified Data.String

data Program = ProgramRoot [Function]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Function
    = Function1 Ident [FuncArgDecl] Ident [LetIn]
    | Function2 Ident [FuncArgDecl] [LetIn]
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FuncArgDecl = FuncArgDeclIdent Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data StructSelector
    = StructSelectorIdent Ident | StructSelector1 StructSelector Ident
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Selector
    = SelectorStructSelector StructSelector
    | Selector1 Ident StructSelector
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data LetIn = LetIn1 Selector Expr | LetInExpr Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data Expr
    = ExprInt Integer
    | ExprDouble Double
    | ExprString String
    | ExprFuncCall FuncCall OptionalHash
    | ExprParen Expr
    | ExprPipe Expr Expr
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FuncCall = FuncCall1 Selector FuncCallArgList
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data OptionalHash = OptionalHash1 | OptionalHash2
  deriving (C.Eq, C.Ord, C.Show, C.Read)

data FuncCallArgList
    = FuncCallArgListContinue Expr FuncCallArgList
    | FuncCallArgListExpr Expr
    | FuncCallArgListEnd
  deriving (C.Eq, C.Ord, C.Show, C.Read)

newtype Ident = Ident String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

